catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('create_book/',views.BookCreate.as_view(),name='create_book'),
    path('book/<int:pk>/',views.BookDetail.as_view(),name='book_detail'),
    path('my_view',views.my_view,name='my_view'),
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('profile/',views.CheckedOutBookByUserView.as_view(),name='profile')
    
]

library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

# www.example.com ----> example.com/app
urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/',include('catalog.urls')),
    path('',RedirectView.as_view(url='catalog/')),
    path('accounts/',include('django.contrib.auth.urls'))
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.
class Genre(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey('Author',on_delete=models.SET_NULL,null=True)
    summery = models.TextField(max_length=600)
    isbn = models.CharField('ISBN',max_length=13,unique=True)
    genre = models.ManyToManyField(Genre)
    language = models.ForeignKey('Language',on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("book_detail",kwargs={"pk": self.pk})

    # More to come

class Author(models.Model):
    first_name = models.CharField(max_length= 20)
    last_name = models.CharField(max_length= 20)
    date_of_birth = models.DateField(null=True,blank=True)

    class Meta:
        ordering = ['last_name','first_name']

    
    def get_absolute_url(self):
        return reverse("author_detail",kwargs={"pk":self.pk}) #kwargs = key-word arguments

    def __str__(self):
        return f"{self.first_name} , {self.last_name}"

import uuid    #uuid --> unique identifier generator
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    book = models.ForeignKey('Book',on_delete=models.RESTRICT,null=True)
    imprint = models.CharField(max_length=100)
    due_back = models.DateField(null=True,blank=True)
    borrower = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)

    LOAN_STATUS = (
        ('m','Maintanance'),
        ('o','On Loan'),
        ('a','Available'),
        ('r','Reserved')
    )

    status  = models.CharField(max_length=1,choices=LOAN_STATUS,blank=True,default='m')

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.title})'

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book,Author,BookInstance,Genre,Language
from django.views.generic import CreateView,DetailView,ListView
from django.contrib.auth.decorators import login_required  # for function based views
from django.contrib.auth.mixins import LoginRequiredMixin # for classed based views
from django.contrib.auth.forms import UserCreationForm #it's technically a form.
from django.urls import reverse_lazy
# Create your views here.


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_avail = BookInstance.objects.filter(status__exact='a').count()  

    context = {
        'num_books':num_books,
        'num_instances':num_instances,
        'num_instances_avail':num_instances_avail
    }

    return render(request,'catalog/index.html',context=context)


class BookCreate(LoginRequiredMixin,CreateView): #book_form.html(inside the module)
    model = Book 
    fields = '__all__'

class BookDetail(DetailView):
    model = Book

# function based views.
@login_required
def my_view(request):
    return render(request,'catalog/my_view.html')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'catalog/signup.html'

class CheckedOutBookByUserView (LoginRequiredMixin,ListView):
    # list  all BookInstances but it will filter based off currently logged in user session.

    model = BookInstance
    template_name = 'catalog/profile.html'
    paginate_by = 5 # 5 books instances per page.

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user)  # .all()

catalog/templates/catalog/book_detail.html
<h1>Details of Book</h1>
{{book}}

catalog/templates/catalog/book_form.html
<h1>Create New Book</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Create">
</form>

catalog/templates/catalog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
             
          </div>
        </div>
      </nav>
    <h2>Books in Library</h2>
    <p>Total Books:{{num_books}}</p>
    <p>Num Available:{{num_instances_avail}}</p>
    {% if user.is_authenticated %}
        <p>You are Logged In</p>
        <p>Welcome: {{user.get_username}}</p>
        <a href="{% url 'logout'%}?next={{request.path}}">logout here</a>
    {% else %}
        <p>You are't logged in</p>
        <a href="{% url 'login'%}?next={{request.path}}">login here</a>
    {% endif %}
</body>
</html>

catalog/templates/catalog/my_view.html
<h1>LoggedIn Users Only!</h1>

catalog/templates/catalog/profile.html
<!-- bookinstances_list ListView -->

<h1>Welcome to your profile</h1>
<h2>Here are your books checked out!</h2>
{% for book in bookinstance_list %}
   <p>{{book}}</p>
{% endfor %}

catalog/templates/catalog/signup.html
<h1>Register a new user here</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="signup">
</form>